<Document>
<Version> 22 </Version>
<JMadonnaVersion> 10.6.1 </JMadonnaVersion>
<Bounds> 0 0 1536 769 </Bounds>
<NotesEditor>
<jeditorpane>
<size>10</size><family>Tahoma</family>





</jeditorpane>
</NotesEditor>
<jmadonna.EquationPanel>
<DocPanel>
</DocPanel>
<jeditorpane>
<size>12</size><family>Serif</family>METHOD RK4

STARTTIME = 0
STOPTIME = 1000
DT = 0.02

init B1 = 0
init B1a = 0
init B1s = 1
init C1 = 0
init A1 = 10000
init A1s = 0

init B2 = 0
init B2a = 0
init B2s = 1
init C2 = 0
init A2 = 10000
init A2s = 0

init A21s = 0
init A21 = 0
init A12s = 0
init A12 = 0

L = 1500
w = 21000
beta1 = 1/5
beta2 = 1/13
alpha1 = 0.001
phi1 = 1/3
phi2 = 1
v = 10000
sigma = 0.001
alpha2 = 1
alpha3 = 0.0005
alpha4 = 0
mu = 1/30

a = 0.3
m = 0.275
r = 0.95

M1 = L*((A1+A1s)/(w+A1+A1s))
P1 = A1s/(1+A1+A1s)

M2 = L*((A2+A2s)/(w+A2+A2s))
P2 = A2s/(1+A2+A2s)

d/dt(B1s) =  (alpha1*P1*B1)+(C1/v)*M1-(phi1*phi2*B1s)
d/dt(B1) = M1-(alpha1*P1*B1)-(C1/v)*M1-beta1*B1
d/dt(B1a) = (beta1*B1)-(beta2*B1a)
d/dt(C1) = (phi1*phi2*B1s)*(sigma*(v-C1))
d/dt(A1s) = (beta2*alpha1*P1*B1a)+(alpha2*(C1/v)*A1)+(alpha3*P1*A1)+(alpha4*A1)-(mu*A1s)-m*A1s+a*A1s
d/dt(A1) = beta2*(1-alpha1*P1)*B1a-(alpha2*(C1/v)*A1)-(alpha3*P1*A1)-(alpha4*A1)-(mu*A1)-m*A1+a*A1

d/dt(B2s) =  (alpha1*P2*B2)+(C2/v)*M2-(phi1*phi2*B2s)
d/dt(B2) = M2-(alpha1*P2*B2)-(C2/v)*M2-beta1*B2
d/dt(B2a) = (beta1*B2)-(beta2*B2a)
d/dt(C2) = (phi1*phi2*B2s)*(sigma*(v-C2))
d/dt(A2s) = (beta2*alpha1*P2*B2a)+(alpha2*(C2/v)*A2)+(alpha3*P2*A2)+(alpha4*A2)-(mu*A2s)-(m*A2s)+a*A2s
d/dt(A2) = beta2*(1-alpha1*P2)*B2a-(alpha2*(C2/v)*A2)-(alpha3*P2*A2)-(alpha4*A2)-(mu*A2)-(m*A2)+a*A2

d/dt(A21s) = m*A2s-a*A1s-r*A21s-mu*A21s
d/dt(A21) = m*A2-a*A1-r*A21-mu*A21
d/dt(A12s) = m*A1s-a*A2s-r*A12s-mu*A12s
d/dt(A12) = m*A1-a*A2-r*A12-mu*A12
</jeditorpane>
</jmadonna.EquationPanel>

<imethod> rk4 </imethod>
<jmadonna.ParameterPanel>
<DocPanel>
</DocPanel>
<ParamSets>
</ParamSets>
</jmadonna.ParameterPanel>
<jmadonna.MultiPanel>
<DocPanel>
</DocPanel>
<DividerPercent> 1.0 </DividerPercent>
<Orientation> -1 </Orientation>
<idx> 0 </idx>
<TabSplitter>
<SelectedIndex> 0 </SelectedIndex>
<graph.COutputFrame>
<DocPanel>
<Name>
Graph 1
</Name>
</DocPanel>

<SingleView>
<graph.COutputView>
<Name> Graph </Name>
<GraphToolBar>
<Legend> 1 </Legend>
<Grid> 1 </Grid>
</GraphToolBar>
<Plot>
<LineWidth> 1 </LineWidth>
<MovableLegend>
<Bounds> 612 58 52 200 </Bounds>
<opaque> true </opaque>
<Color> 255 255 255 </Color>
<border> true </border>
</MovableLegend>
</Plot>
<OV_XVAR>
<VI_SYMBOL> TIME </VI_SYMBOL>
</OV_XVAR>
<OV_YVARS>
<OV_YVAR_I>
<VI_SYMBOL> B1s </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> B1 </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> B1a </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> C1 </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> A1s </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> A1 </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> B2 </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> B2a </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> B2s </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> C2 </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> A2 </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
<OV_YVAR_I>
<VI_SYMBOL> A2s </VI_SYMBOL>
<VI_SHOW> true </VI_SHOW>
<VI_Y2AXIS> false </VI_Y2AXIS>
</OV_YVAR_I>
</OV_YVARS>
<OV_TABLE> false </OV_TABLE>
<OV_FFT> false </OV_FFT>
<OV_COLORS> true </OV_COLORS>
<OV_STYLES> false </OV_STYLES>
<OV_OSCMODE> false </OV_OSCMODE>
<OV_LINES> true </OV_LINES>
<OV_POINTS> false </OV_POINTS>
<OV_GRID> true </OV_GRID>
<OV_DBTN> true </OV_DBTN>
<OV_LEGEND> true </OV_LEGEND>
<OV_PARAMS> false </OV_PARAMS>
<OV_READOUT> false </OV_READOUT>
<OV_INITCOND> false </OV_INITCOND>
<OV_RDOUTFXFY> 0.0 0.0 </OV_RDOUTFXFY>
<OV_ZSNORMAL>
</OV_ZSNORMAL>
<OV_ZSFFT>
<ZS_SIZE> 1 </ZS_SIZE>
<ZS_I>
<ZS_XLOG> true </ZS_XLOG>
<ZS_Y1LOG> false </ZS_Y1LOG>
<ZS_Y2LOG> false </ZS_Y2LOG>
</ZS_I>
</OV_ZSFFT>
<OV_ZSOSCMODE>
</OV_ZSOSCMODE>
<OV_AUTOLABEL> 0 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 1 1 </OV_AUTOLABEL>
<OV_AUTOLABEL> 2 1 </OV_AUTOLABEL>
<OV_X1LABELS>  TIME </OV_X1LABELS>
<OV_Y1LABELS>  B1s, B1, B1a, C1, A1s, A1, B2, B2a, B2s, C2, A2, A2s </OV_Y1LABELS>
<OV_Y2LABELS>   </OV_Y2LABELS>
<OV_LEGENDXY> 0.30000001192092896 0.5 </OV_LEGENDXY>
<OV_PARAMSXY> 0.30000001192092896 0.5 </OV_PARAMSXY>
<OV_COLORTABLE> 0 <OV_COLORTABLE>
</graph.COutputView>
</SingleView>
</graph.COutputFrame>
</TabSplitter>
<idx> 1 </idx>
<TabSplitter>
<SelectedIndex> -1 </SelectedIndex>
</TabSplitter>
</jmadonna.MultiPanel>

</Document>
